### ISSUE TITLE
Oraclepositional and named binds cannot be intermixed(==7.1)

### ISSUE THREAD

**Issue by sawantsaurabh** [oracle/python-cx_Oracle#292]
Getting above error for cx_oracle 7.1. 
Any solution to fix it? 
I m using 
curr.setinputsizes(*inputSizes)
curr.execute(query)
to update query

**Comment by anthony-tuininga** [comment]
Can you provide the code and input data that you are using to reproduce the problem? Without that I'm left guessing!

**Comment by sawantsaurabh** [comment]
Please find the below code and test data
[DEBUG.zip](https://github.com/oracle/python-cx_Oracle/files/3052986/DEBUG.zip)

**Comment by anthony-tuininga** [comment]
I just tried your code. I fixed the syntax error (missing parenthesis) but I don't know what the duplicate_drop_df is supposed to refer to (line 22). Can you correct that?

**Comment by sawantsaurabh** [comment]
[DEBUG.zip](https://github.com/oracle/python-cx_Oracle/files/3057282/DEBUG.zip)
Please find the updated code.
Still facing the issue after making your suggested changes.

**Comment by anthony-tuininga** [comment]
With the updated code I get an error at line 56 -- and the error is legitimate. You are calling ``cursor.setinputsizes()`` with positional arguments and then calling ``cursor.execute()`` with named arguments. That's not supported. You need to either change your ``setinputsizes()`` to use named arguments or your ``cursor.execute()`` call to use positional arguments. I hope that makes sense!

**Comment by anthony-tuininga** [comment]
Considering the lack of response I figure your question has been answered. If not, please advise! Thanks.
